"""create_table_media

Revision ID: 1ab2461511b0
Revises: a86b667f2580
Create Date: 2024-10-05 14:09:25.737265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab2461511b0'
down_revision: Union[str, None] = 'a86b667f2580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('ENDLESS_SPACE', 'ENDLESS_SPACE_2', 'ENDLESS_LEGEND', 'DUNGEON_OF_THE_ENDLESS', 'ENDLESS_DUNGEON', name='medianame'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
