name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifie le code
        uses: actions/checkout@v2

      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances depuis le fichier requirements.txt

      - name: Exécuter les tests
        run: |
          pytest
