"""add_url_column_to_planet_table

Revision ID: 870d22f9b398
Revises: b59f925e94ae
Create Date: 2025-01-25 17:19:06.490872

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "870d22f9b398"
down_revision: Union[str, None] = "b59f925e94ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("planet", sa.Column("url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("planet", "url")
    # ### end Alembic commands ###
