"""add_url_column_to_faction_description_table

Revision ID: 65cf1280344d
Revises: f356493bd064
Create Date: 2025-01-26 21:09:03.225713

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65cf1280344d"
down_revision: Union[str, None] = "f356493bd064"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "factions_descriptions", sa.Column("url", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("factions_descriptions", "url")
    # ### end Alembic commands ###
