"""add_url_column_to_faction_table

Revision ID: f356493bd064
Revises: 870d22f9b398
Create Date: 2025-01-25 22:32:40.146699

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f356493bd064"
down_revision: Union[str, None] = "870d22f9b398"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("factions", sa.Column("url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("factions", "url")
    # ### end Alembic commands ###
